-- RentFlow — initial schema (MySQL / MariaDB)
-- Generated by hand from prisma/schema.prisma (see that file for the source
-- of truth and field-level comments). Applying this file is equivalent to
-- `prisma migrate deploy` against an empty database.
--
-- Notes on the Postgres -> MySQL port:
--   * Prisma enums have no MySQL type equivalent, so each becomes an inline
--     ENUM(...) on the column itself (matching what `prisma migrate dev`
--     itself generates for the mysql provider).
--   * Plain (un-annotated) `String` fields map to VARCHAR(191) — Prisma's
--     own default column size for MySQL, chosen so every String column can
--     still be used in a unique index/foreign key under InnoDB's key-length
--     limit. Fields explicitly marked `@db.Text` in schema.prisma map to
--     MySQL TEXT and are never part of an index.
--   * `@default(uuid())` id/FK columns get no DB-level default — Prisma
--     Client always generates and supplies the UUID on insert, so there's
--     no need for a MySQL-side UUID() default (and MySQL's UUID() output
--     isn't guaranteed to match Prisma's v4 UUIDs anyway).
--   * DateTime -> DATETIME(3); Json/Jsonb -> JSON; Decimal is unchanged.

-- ============================================================================
-- Tenancy
-- ============================================================================

CREATE TABLE `agencies` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `domain` VARCHAR(191),
    `logoUrl` VARCHAR(191),
    `coverImageUrl` VARCHAR(191),
    `description` TEXT,
    `email` VARCHAR(191),
    `phone` VARCHAR(191),
    `whatsapp` VARCHAR(191),
    `address` VARCHAR(191),
    `city` VARCHAR(191),
    `country` VARCHAR(191) NOT NULL DEFAULT 'Morocco',
    `currency` VARCHAR(191) NOT NULL DEFAULT 'MAD',
    `timezone` VARCHAR(191) NOT NULL DEFAULT 'Africa/Casablanca',
    `primaryColor` VARCHAR(191) NOT NULL DEFAULT '#2563EB',
    `accentColor` VARCHAR(191) NOT NULL DEFAULT '#10B981',
    `plan` ENUM('TRIAL','STARTER','PRO','ENTERPRISE') NOT NULL DEFAULT 'TRIAL',
    `status` ENUM('TRIAL','ACTIVE','SUSPENDED','CANCELLED') NOT NULL DEFAULT 'TRIAL',
    `trialEndsAt` DATETIME(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3),

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `agencies_slug_key` ON `agencies`(`slug`);
CREATE UNIQUE INDEX `agencies_domain_key` ON `agencies`(`domain`);
CREATE INDEX `agencies_status_idx` ON `agencies`(`status`);

-- ============================================================================
-- Auth / Staff / RBAC
-- ============================================================================

CREATE TABLE `permissions` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `label` VARCHAR(191) NOT NULL,
    `group` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `permissions_key_key` ON `permissions`(`key`);

CREATE TABLE `roles` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191),
    `isSystem` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `roles_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `roles_agencyId_name_key` ON `roles`(`agencyId`, `name`);

CREATE TABLE `role_permissions` (
    `id` VARCHAR(191) NOT NULL,
    `roleId` VARCHAR(191) NOT NULL,
    `permissionId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `role_permissions_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `roles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `role_permissions_permissionId_fkey` FOREIGN KEY (`permissionId`) REFERENCES `permissions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `role_permissions_roleId_permissionId_key` ON `role_permissions`(`roleId`, `permissionId`);

CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `roleId` VARCHAR(191),
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `emailVerified` BOOLEAN NOT NULL DEFAULT false,
    `image` VARCHAR(191),
    `phone` VARCHAR(191),
    `status` ENUM('ACTIVE','INVITED','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
    `lastLoginAt` DATETIME(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `users_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `users_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `roles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `users_email_key` ON `users`(`email`);
CREATE INDEX `users_agencyId_idx` ON `users`(`agencyId`);

CREATE TABLE `sessions` (
    `id` VARCHAR(191) NOT NULL,
    `token` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `ipAddress` VARCHAR(191),
    `userAgent` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `sessions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `sessions_token_key` ON `sessions`(`token`);

CREATE TABLE `accounts` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `accountId` VARCHAR(191) NOT NULL,
    `providerId` VARCHAR(191) NOT NULL,
    `issuer` VARCHAR(191) NOT NULL,
    `accessToken` TEXT,
    `refreshToken` TEXT,
    `idToken` TEXT,
    `accessTokenExpiresAt` DATETIME(3),
    `refreshTokenExpiresAt` DATETIME(3),
    `scope` VARCHAR(191),
    `password` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `accounts_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `accounts_providerId_issuer_accountId_key` ON `accounts`(`providerId`, `issuer`, `accountId`);

CREATE TABLE `verifications` (
    `id` VARCHAR(191) NOT NULL,
    `identifier` VARCHAR(191) NOT NULL,
    `value` VARCHAR(191) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `verifications_identifier_idx` ON `verifications`(`identifier`);

-- ============================================================================
-- Fleet
-- ============================================================================

CREATE TABLE `vehicle_categories` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `type` ENUM('CAR','MOTORCYCLE') NOT NULL,
    `description` VARCHAR(191),
    `icon` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `vehicle_categories_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `vehicle_categories_agencyId_slug_key` ON `vehicle_categories`(`agencyId`, `slug`);

CREATE TABLE `vehicles` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `categoryId` VARCHAR(191),
    `type` ENUM('CAR','MOTORCYCLE') NOT NULL,
    `brand` VARCHAR(191) NOT NULL,
    `model` VARCHAR(191) NOT NULL,
    `year` INTEGER NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `transmission` ENUM('AUTOMATIC','MANUAL','SEMI_AUTOMATIC') NOT NULL,
    `fuel` ENUM('PETROL','DIESEL','ELECTRIC','HYBRID') NOT NULL,
    `horsepower` INTEGER,
    `engineSize` VARCHAR(191),
    `seats` INTEGER,
    `doors` INTEGER,
    `color` VARCHAR(191),
    `licensePlate` VARCHAR(191),
    `mileage` INTEGER,
    `hasAC` BOOLEAN NOT NULL DEFAULT true,
    `hasBluetooth` BOOLEAN NOT NULL DEFAULT false,
    `hasGPS` BOOLEAN NOT NULL DEFAULT false,
    `unlimitedKm` BOOLEAN NOT NULL DEFAULT false,
    `mileageLimitPerDay` INTEGER,
    `insuranceIncluded` BOOLEAN NOT NULL DEFAULT true,
    `depositAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `description` TEXT,
    `status` ENUM('AVAILABLE','BOOKED','MAINTENANCE','HIDDEN') NOT NULL DEFAULT 'AVAILABLE',
    `featured` BOOLEAN NOT NULL DEFAULT false,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `insuranceExpiresAt` DATETIME(3),
    `registrationExpiresAt` DATETIME(3),
    `lastOilChangeAt` DATETIME(3),
    `lastOilChangeMileage` INTEGER,
    `maintenanceNotes` TEXT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `vehicles_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `vehicles_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `vehicle_categories`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `vehicles_agencyId_slug_key` ON `vehicles`(`agencyId`, `slug`);
CREATE INDEX `vehicles_agencyId_status_idx` ON `vehicles`(`agencyId`, `status`);
CREATE INDEX `vehicles_agencyId_type_idx` ON `vehicles`(`agencyId`, `type`);
CREATE INDEX `vehicles_agencyId_featured_idx` ON `vehicles`(`agencyId`, `featured`);

CREATE TABLE `vehicle_images` (
    `id` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `url` VARCHAR(191) NOT NULL,
    `publicId` VARCHAR(191),
    `alt` VARCHAR(191),
    `position` INTEGER NOT NULL DEFAULT 0,
    `isCover` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `vehicle_images_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `vehicle_images_vehicleId_idx` ON `vehicle_images`(`vehicleId`);

CREATE TABLE `vehicle_pricing` (
    `id` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `period` ENUM('DAILY','WEEKLY','MONTHLY','WEEKEND','HOLIDAY','SEASONAL') NOT NULL,
    `amount` DECIMAL(10,2) NOT NULL,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'MAD',
    `discountPercent` DECIMAL(5,2),
    `startDate` DATETIME(3),
    `endDate` DATETIME(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `vehicle_pricing_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `vehicle_pricing_vehicleId_period_idx` ON `vehicle_pricing`(`vehicleId`, `period`);

-- ============================================================================
-- Customers
-- ============================================================================

CREATE TABLE `customers` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191),
    `phone` VARCHAR(191),
    `whatsapp` VARCHAR(191),
    `country` VARCHAR(191),
    `city` VARCHAR(191),
    `licenseNumber` VARCHAR(191),
    `licenseCountry` VARCHAR(191),
    `licenseExpiry` DATETIME(3),
    `passportNumber` VARCHAR(191),
    `dateOfBirth` DATETIME(3),
    `status` ENUM('REGULAR','VIP','BLACKLISTED') NOT NULL DEFAULT 'REGULAR',
    `notes` TEXT,
    `totalBookings` INTEGER NOT NULL DEFAULT 0,
    `totalRevenue` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `customers_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `customers_agencyId_status_idx` ON `customers`(`agencyId`, `status`);
CREATE INDEX `customers_agencyId_phone_idx` ON `customers`(`agencyId`, `phone`);

-- ============================================================================
-- Coupons (created before reservations, which reference them)
-- ============================================================================

CREATE TABLE `coupons` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `code` VARCHAR(191) NOT NULL,
    `type` ENUM('PERCENTAGE','FIXED') NOT NULL,
    `value` DECIMAL(10,2) NOT NULL,
    `maxUses` INTEGER,
    `usedCount` INTEGER NOT NULL DEFAULT 0,
    `minRentalDays` INTEGER,
    `startsAt` DATETIME(3),
    `expiresAt` DATETIME(3),
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `coupons_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `coupons_agencyId_code_key` ON `coupons`(`agencyId`, `code`);

-- ============================================================================
-- Reservations
-- ============================================================================

CREATE TABLE `reservations` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `reservationNumber` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `customerId` VARCHAR(191) NOT NULL,
    `status` ENUM('PENDING','CONFIRMED','ONGOING','COMPLETED','CANCELLED','NO_SHOW') NOT NULL DEFAULT 'PENDING',
    `source` ENUM('WEBSITE','WHATSAPP','INSTAGRAM','FACEBOOK','GOOGLE','PHONE','WALK_IN','OTHER') NOT NULL DEFAULT 'WEBSITE',
    `pickupDate` DATETIME(3) NOT NULL,
    `returnDate` DATETIME(3) NOT NULL,
    `pickupTime` VARCHAR(191),
    `returnTime` VARCHAR(191),
    `pickupCity` VARCHAR(191),
    `returnCity` VARCHAR(191),
    `flightNumber` VARCHAR(191),
    `driverAge` INTEGER,
    `licenseCountry` VARCHAR(191),
    `additionalDriver` BOOLEAN NOT NULL DEFAULT false,
    `message` TEXT,
    `durationDays` INTEGER NOT NULL,
    `basePrice` DECIMAL(10,2) NOT NULL,
    `discountAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `extrasAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `totalPrice` DECIMAL(10,2) NOT NULL,
    `depositAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `paymentStatus` ENUM('UNPAID','PARTIALLY_PAID','PAID','REFUNDED') NOT NULL DEFAULT 'UNPAID',
    `couponId` VARCHAR(191),
    `createdById` VARCHAR(191),
    `notes` TEXT,
    `cancelledAt` DATETIME(3),
    `cancelledReason` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `reservations_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `reservations_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `reservations_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `reservations_couponId_fkey` FOREIGN KEY (`couponId`) REFERENCES `coupons`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `reservations_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `reservations_reservationNumber_key` ON `reservations`(`reservationNumber`);
CREATE INDEX `reservations_agencyId_status_idx` ON `reservations`(`agencyId`, `status`);
CREATE INDEX `reservations_vehicleId_pickupDate_returnDate_idx` ON `reservations`(`vehicleId`, `pickupDate`, `returnDate`);
CREATE INDEX `reservations_agencyId_createdAt_idx` ON `reservations`(`agencyId`, `createdAt`);

CREATE TABLE `reservation_status_logs` (
    `id` VARCHAR(191) NOT NULL,
    `reservationId` VARCHAR(191) NOT NULL,
    `status` ENUM('PENDING','CONFIRMED','ONGOING','COMPLETED','CANCELLED','NO_SHOW') NOT NULL,
    `note` VARCHAR(191),
    `changedById` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `reservation_status_logs_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `reservations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `reservation_status_logs_changedById_fkey` FOREIGN KEY (`changedById`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `reservation_status_logs_reservationId_idx` ON `reservation_status_logs`(`reservationId`);

-- ============================================================================
-- Vehicle availability (needs reservations for its optional FK)
-- ============================================================================

CREATE TABLE `vehicle_availability` (
    `id` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `startDate` DATETIME(3) NOT NULL,
    `endDate` DATETIME(3) NOT NULL,
    `status` ENUM('AVAILABLE','BOOKED','BLOCKED','MAINTENANCE') NOT NULL DEFAULT 'BLOCKED',
    `reason` VARCHAR(191),
    `reservationId` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `vehicle_availability_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `vehicle_availability_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `reservations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `vehicle_availability_vehicleId_startDate_endDate_idx` ON `vehicle_availability`(`vehicleId`, `startDate`, `endDate`);

-- ============================================================================
-- Billing
-- ============================================================================

CREATE TABLE `invoices` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `reservationId` VARCHAR(191) NOT NULL,
    `customerId` VARCHAR(191) NOT NULL,
    `invoiceNumber` VARCHAR(191) NOT NULL,
    `status` ENUM('DRAFT','SENT','PAID','OVERDUE','CANCELLED') NOT NULL DEFAULT 'DRAFT',
    `subtotal` DECIMAL(10,2) NOT NULL,
    `taxAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `discountAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `totalAmount` DECIMAL(10,2) NOT NULL,
    `issuedAt` DATETIME(3),
    `dueAt` DATETIME(3),
    `paidAt` DATETIME(3),
    `pdfUrl` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `invoices_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `invoices_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `reservations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `invoices_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `invoices_reservationId_key` ON `invoices`(`reservationId`);
CREATE UNIQUE INDEX `invoices_invoiceNumber_key` ON `invoices`(`invoiceNumber`);
CREATE INDEX `invoices_agencyId_status_idx` ON `invoices`(`agencyId`, `status`);

CREATE TABLE `payments` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `reservationId` VARCHAR(191) NOT NULL,
    `invoiceId` VARCHAR(191),
    `amount` DECIMAL(10,2) NOT NULL,
    `method` ENUM('CASH','CARD','STRIPE','PAYPAL','CMI','BANK_TRANSFER') NOT NULL,
    `status` ENUM('PENDING','SUCCEEDED','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
    `transactionRef` VARCHAR(191),
    `paidAt` DATETIME(3),
    `notes` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `payments_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `payments_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `reservations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `payments_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `invoices`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `payments_agencyId_status_idx` ON `payments`(`agencyId`, `status`);

-- ============================================================================
-- Engagement
-- ============================================================================

CREATE TABLE `notifications` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `channel` ENUM('EMAIL','SMS','WHATSAPP','SYSTEM') NOT NULL,
    `status` ENUM('PENDING','SENT','FAILED','READ') NOT NULL DEFAULT 'PENDING',
    `title` VARCHAR(191) NOT NULL,
    `body` TEXT NOT NULL,
    `relatedReservationId` VARCHAR(191),
    `recipientUserId` VARCHAR(191),
    `recipientEmail` VARCHAR(191),
    `recipientPhone` VARCHAR(191),
    `sentAt` DATETIME(3),
    `readAt` DATETIME(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `notifications_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `notifications_relatedReservationId_fkey` FOREIGN KEY (`relatedReservationId`) REFERENCES `reservations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `notifications_agencyId_status_idx` ON `notifications`(`agencyId`, `status`);

CREATE TABLE `reviews` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `customerId` VARCHAR(191) NOT NULL,
    `rating` INTEGER NOT NULL,
    `comment` TEXT,
    `isPublished` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `reviews_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `reviews_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `reviews_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `reviews_agencyId_isPublished_idx` ON `reviews`(`agencyId`, `isPublished`);
CREATE INDEX `reviews_vehicleId_idx` ON `reviews`(`vehicleId`);

-- ============================================================================
-- Maintenance
-- ============================================================================

CREATE TABLE `maintenances` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `type` ENUM('OIL_CHANGE','INSPECTION','REPAIR','TIRE_CHANGE','INSURANCE_RENEWAL','REGISTRATION_RENEWAL','OTHER') NOT NULL,
    `status` ENUM('SCHEDULED','IN_PROGRESS','COMPLETED','OVERDUE') NOT NULL DEFAULT 'SCHEDULED',
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT,
    `scheduledDate` DATETIME(3),
    `completedDate` DATETIME(3),
    `cost` DECIMAL(10,2),
    `mileageAt` INTEGER,
    `performedById` VARCHAR(191),
    `notes` TEXT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `maintenances_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `maintenances_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `maintenances_performedById_fkey` FOREIGN KEY (`performedById`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `maintenances_agencyId_status_idx` ON `maintenances`(`agencyId`, `status`);
CREATE INDEX `maintenances_vehicleId_idx` ON `maintenances`(`vehicleId`);

-- ============================================================================
-- Platform: settings, logs
-- ============================================================================

CREATE TABLE `settings` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `bookingLeadTimeHours` INTEGER NOT NULL DEFAULT 2,
    `minRentalDays` INTEGER NOT NULL DEFAULT 1,
    `cancellationPolicy` TEXT,
    `fuelPolicy` TEXT,
    `taxRatePercent` DECIMAL(5,2) NOT NULL DEFAULT 0,
    `depositRequired` BOOLEAN NOT NULL DEFAULT true,
    `autoConfirmReservations` BOOLEAN NOT NULL DEFAULT false,
    `notifyEmail` BOOLEAN NOT NULL DEFAULT true,
    `notifyWhatsapp` BOOLEAN NOT NULL DEFAULT false,
    `notifySms` BOOLEAN NOT NULL DEFAULT false,
    `socialInstagram` VARCHAR(191),
    `socialFacebook` VARCHAR(191),
    `socialWhatsappNumber` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`),
    CONSTRAINT `settings_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE UNIQUE INDEX `settings_agencyId_key` ON `settings`(`agencyId`);

CREATE TABLE `activity_logs` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191),
    `action` VARCHAR(191) NOT NULL,
    `entityType` VARCHAR(191) NOT NULL,
    `entityId` VARCHAR(191),
    `metadata` JSON,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `activity_logs_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `activity_logs_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `activity_logs_agencyId_createdAt_idx` ON `activity_logs`(`agencyId`, `createdAt`);

CREATE TABLE `audit_logs` (
    `id` VARCHAR(191) NOT NULL,
    `agencyId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191),
    `action` VARCHAR(191) NOT NULL,
    `entityType` VARCHAR(191) NOT NULL,
    `entityId` VARCHAR(191),
    `before` JSON,
    `after` JSON,
    `ipAddress` VARCHAR(191),
    `userAgent` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`),
    CONSTRAINT `audit_logs_agencyId_fkey` FOREIGN KEY (`agencyId`) REFERENCES `agencies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `audit_logs_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX `audit_logs_agencyId_entityType_entityId_idx` ON `audit_logs`(`agencyId`, `entityType`, `entityId`);
